config/routes.rb
  Rails.application.routes.draw do


   get 'survey' => 'survey#index', as: :survey_index
   get 'survey/:id' => 'survey#show', as: :survey
   get 'products' => 'survey#products', as: :products
   root 'survey#home'

  end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers

end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :surveys
  has_many :responses
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def survey_results
    @responses = Responses.all
  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController

  def home
  end

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def products
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdsource Fashion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            <h1 class="masthead-brand">Crowdsource Fashion</h1>
            <nav>
              <ul class="nav masthead-nav">
                <li><%= link_to "Home", root_path%></li>
                <li><%= link_to "Products", products_path%></li>
                <li><%= link_to "Surveys", survey_index_path %></li>
              </ul>
            </nav>
          </div>
        </div>

        <div class="inner cover">
          <hr>
          <br>

        <%= yield %>


        </div>
<div class="mastfoot">
  <div class="inner">
    <hr>
    <p>Copyright 2016           <a href="#">Contact</a></p>
  </div>
</div>

</div>

</div>

</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/survey/_questionform.html.erb
<%= form_for @question do |q| %>
<% g.answers.each do |a| %>
<button> 

app/views/survey/home.html.erb
<div class="frontpagemainclass">

<br>
<br>
<h1>Welcome to Crowdsource Fashion<br> </h1>

You select the best products!<br>
    <br>
        <br>
            <br>
                <br>
                    <br>
                        <br>

                            <br>
                                <br>
                                    <br>
                                        <br>
    <br>
                              <br>

</div>

app/views/survey/index.html.erb
<h1>The Crowdsource Fashion Surveys</h1>
<p class="lead">
    By doing a survey you:<br>
    <br>
    Receive a guaranteed discount code<br>
    Have a chance of winning one of our brand new "First Edition" bags!</p>
    <p class="lead">
<br>
<br>
<% @surveys.each do |survey| %>
    <a><%= link_to survey.title, survey_path(survey.id) %></a>
<% end %>
</p>

app/views/survey/products.html.erb
<h1>Our product overview:</h1>
<p class="lead">

The choice of January:<br><br>
<img src="http://handbags.sell4value.com/bags.png" width="200p" height="auto"><br><br>
The choice of February:<br><br>
<img src="http://donnabelladesigns.com/images/11/products/Farrah-Group-shot.png" width="200p" height="auto"><br><br>

</p>

app/views/survey/show.html.erb
<h1><%= @survey.title %></h1>


<%= form_for @responses do |f| %>
<% @survey.questions.each do |q| %>
<h2><%= q.title %></h2>
  <% q.answers.each do |answer| %>
  <br>
  <br>
  <%= radio_button_tag("question[#{q.id}]", answer.title ) %>
    <%= label_tag(:title, answer.title) %>
  <% end %>
  <br><br>
  <% end %>
  <br><br>
  <%= f.submit %>
<% end %>

app/views/survey/surv.html.erb
<h1>surv<br> </h1>


<p class="lead">
    The survey comes here!!
    <p class="lead">
<br>
<br>
<a href="#" class="btn btn-lg btn-default">Start the survey!</a>
</p>